language: c
compiler: gcc
script: make
dist: focal
before_script:
- sudo apt-get update -qq
- sudo apt-get install -qq cmake libhiredis-dev libxml2-dev libmysqlclient-dev cmake
- sudo apt-get remove libgnutls-dev
- git clone https://github.com/bmybbs/bmybbs.git
- sudo mkdir -p /home/bbs/bin
- sudo mv bmybbs /home/bmybbs
- (cd /home/bmybbs; git checkout feature/bmyapp; cd ythtlib; sudo make install; cd ../libythtbbs; sudo make install; cd ../software; tar zxf libghthash-0.5.0-x86_64.tar.gz; cd libghthash-0.5.0-x86_64; ./configure; make; sudo make install)
- git clone https://github.com/davidmoreno/onion
- (mkdir onion-build; cd onion-build; cmake ../onion; make; cd src/onion; sudo make install)
- git clone https://github.com/json-c/json-c.git
- (make json-c-build; cd json-c-build; cmake ../json-c; make; sudo make install)

env:
  global:
   - secure: "U3QvhmX28dckrJK5jB8v36Z2IJA6TeJmCf7ZZ34Dxhkb4dbYJYPHthuL8nvVrofb/m8v0qezX96mlpbGjdfIqnCVq75PwaUib+jOisaqeeNW7VL1Mviakg7x8MrTgSzCdIQfl8hiauAB7gICAUXkyp4oMf/kmJlm7Xic0koHFl4="

addons:
  coverity_scan:
    project:
      name: "bmybbs/api"
      description: "Build submitted via Travis CI"
    notification_email:
      secure: "KQl4G+qtZ1U/VFCOIADdzBzpMwOT1yQUlYzrnPAYItGRMRSgT2I+QKEF4aU7cWpip1ltj8y0nDrZOIAa5fKmy4aRCJI7bHKkq+Al2wX5DPEz3+xSWegFck9/GpEUhvzWK4lQ7pbV/ySAX/2U2rUNqoS8EVQjDFICPTwGXGLahvE="
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: master
